name: Build-Push&Deploy-xxx

on:
  push:
    branches: [ V2-deploy-xxx ] # this feature branch and but i need after succesful test like vite & playwright, merge to main branch automatically trigger the deploy workflow

env:
  REGISTRY_NAME: registry.digitalocean.com/dev-services
  repository: full-stack

permissions:
  contents: read
  packages: write

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      #  Log in to DigitalOcean Container Registry
      - name: doctl install
        uses: digitalocean/action@v2
        with:
          token: ${{ secrets.DO_TOKEN }}

      - name: Log in to DOCR
        run: doctl registry login --expiry-seconds 1200

      # Build & push the image
      - name: Build and push image
        run: |
          IMAGE=${{ env.REGISTRY_NAME }}/${{ env.repository }}:galaxy-frontend
          docker build -f docker/Dockerfile -t $IMAGE .
          docker push $IMAGE

      # Deploy to App Platform
      - name: Deploy App
        uses: digitalocean/app_action/deploy@v2
        with:
          token: ${{ secrets.DO_TOKEN }}
          # Optional: specify the image digest if you want an exact version.
